### ISSUE TITLE
getting mongodb error

### ISSUE THREAD

**Issue by chethanrraj90** [MohdSaif-1807/Network-Intrusion-Detection-System-Using-Machine-Learning-and-Deep-Learning#1]
i am getting below error please help me
![image](https://user-images.githubusercontent.com/71137457/233018522-668a9451-c5c7-4429-a648-034db9d246dc.png)

and also sir please explain how and what to do in **Step-2 : Create a .env file and set up the dovenv variable which is used in app.js (or) remove dotenv variables from app.js and set the links like mongoDB link etc.**  where to add mongodb query link in app.js?

i used both the methods
but dint understand 2nd step and unable to login and use the features.

please help sir..

**Comment by MohdSaif-1807** [comment]
OK, Man I have seen the issue which you are facing it's just deprecation of
the libraries which we have used in our project.. Due to which you are
facing the issue. Wait for some time I will try to update the libraries and
will be pushing the docker image soon.. And regarding the .env you yourself
have to generate the values for the .env variables by creating certain
accounts in various platforms as mongodb Atlas or local, Google security,
etc.. The information regarding it you can get from the app.js file where
we have use variables of .env..

**Comment by chethanrraj90** [comment]
Ok sir, looking forward to you

**Comment by MohdSaif-1807** [comment]
Done!! Updated the Docker Image Now you can run the docker container to view the
![Screenshot (1711)](https://user-images.githubusercontent.com/113005309/233822039-5aa2791d-0071-4b47-ba5b-944c5c375c81.png)
 application. And for the .env file there are variables which is listed in the following image where you have to required values that are encoded in angular brackets.

**Comment by chethanrraj90** [comment]
thank you sir..
docker run --publish 3000:3000 saif0786/nids
is the command for docker method?
but getting error
![image](https://user-images.githubusercontent.com/71137457/233834532-9823be5d-0488-481d-98bf-944509fd5168.png)
please share updated command for docker

**Comment by MohdSaif-1807** [comment]
Before running this command did you have removed all existing images of
saif0786/nids from docker desktop?

**Comment by MohdSaif-1807** [comment]
If not then remove all the existing images of saif0786/nids from docker
desktop and then run the command remember removal of images from docker
desktop means deleting of those images from your docker desktop.

**Comment by chethanrraj90** [comment]
Yes sir now it is running successfully thank you so much for your help..

**Comment by MohdSaif-1807** [comment]
Glad to hear it!

**Comment by chethanrraj90** [comment]
![image](https://user-images.githubusercontent.com/71137457/234827330-a1fc585f-6de9-4bdc-8430-0eb9de80ecc4.png)
hi sir
in predict section 2nd feature that is OPEN CSV
i giving csv file but in return it is returning the same uploaded file when i download.
it is not returning updated file with type of attack for each row.

what may be the problem

**Comment by MohdSaif-1807** [comment]
Ok Man, So the problem may be related to the type of input you are trying
to supply since you have selected open csv as a method to give input to the
system you must have a knowledge about the type of input required by the
system. And another problem would be slowness of your system. Your system
may be slow due to which it may take more time to process the data.

**Comment by chethanrraj90** [comment]
so basically i just gave same data what you have given in the video with same rows same attributes same values, that too with same file name. https://drive.google.com/file/d/1o76ZBdZ0vIAFx2EHPrKCtG12oNUeEsdu/view

**Comment by MohdSaif-1807** [comment]
Ok So in that case you try to check the console statements as I have
mention completed as the console statement when the file is successfully
updated try to download the file after you see the completed as the
statement in your console and check the csv file.

**Comment by chethanrraj90** [comment]
okay sir

**Comment by vaishnavichannegowda** [comment]
![Uploading network error.png…]()
Hi sir,
i entered the network parameters i am only getting partial output where the knn description and binary,multi class attacks are not shown how to resolve it please help me with this i have demo tomorrow
