### ISSUE TITLE
Compilation issues

### ISSUE THREAD

**Issue by sadz1z** [MohdSaif-1807/Network-Intrusion-Detection-System-Using-Machine-Learning-and-Deep-Learning#4]
Hello, could you please provide more details on how to run the code? I am not very familiar with Method 2 and look forward to your prompt reply

**Comment by MohdSaif-1807** [comment]
For the method-2,
first you have to clone the repository or you have to take .zip file and extract the file and install the the node_modules for the project using the command `npm i`,
after which you have to create a `.env` file with the variables as follows:
CLIENT_ID=<google client id>
CLIENT_SECRET=<google client secret>
DB_LINK=<mongo db atlas URL>
CALL_BACK_URL=<google call back url>
URL= <google api url>
add valid values in place of angular brackets,helper text,
the above variables for using google has been used in order to implement the login with google feature.
after completion of above steps you can run the project using node app.js

**Comment by sadz1z** [comment]
What a fast reply! My. env file was set based on your previous reply, as shown in the picture. Now, after running it, the following result appears. I'm not sure what the reason is
![2](https://github.com/MohdSaif-1807/Network-Intrusion-Detection-System-Using-Machine-Learning-and-Deep-Learning/assets/136089710/328d8d71-397f-48c8-8606-a0b1db71232d)
![1](https://github.com/MohdSaif-1807/Network-Intrusion-Detection-System-Using-Machine-Learning-and-Deep-Learning/assets/136089710/017b6c4d-703b-44b8-b091-8b095e8d1b1e)

**Comment by MohdSaif-1807** [comment]
see in place of angular brackets and helper text you have to add valid values, such as for eg in case DB_LINK you have to provide it with the value as mongodb atlas url similiarly you have to fill all the .env variables with valid values
